title: 'Tax Academy Singapore'
description: 'Tax Academy of Singapore is a not-for-profit institution set up by the Inland Revenue Authority of Singapore in collaboration with the international accounting firms - Deloitte & Touche, Ernst & Young, KPMG and PricewaterhouseCoopers, the Institute of Singapore Chartered Accountants and the Law Society of Singapore'
url: 'https://www.taxacademy.sg'
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
resources_name: resources
paginate: 12
paginate_path: '/resources/page:num'
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
favicon: /images/favicon.ico
google-analytics: null
permalink: none
baseurl: ""
defaults:
  - scope:
      path: ""
    values:
      layout: page
staging: https://staging-iras-tax-academy.netlify.app
prod: https://production-iras-tax-academy.netlify.app
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
